### ISSUE TITLE
PhenoWatch: Non Acer Genera

### ISSUE THREAD

**Issue by tmuhich** [zhulabgroup/phenology-website#24]
When people select a genus that was not Acer, the app almost always crashed.  When Acer was selected, it usually worked.  This needs to be fixed.

**Comment by tpanja** [comment]
This is happening because there are too many data points for the non Acer genuses. I will see what I need to do.

**Comment by tpanja** [comment]
I mitigated this issue for now by not using the years with insufficient data in the boxplot graph. Will push updates.
